# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/cmake-4.0.1-linux-x86_64/bin/cmake

# The command to remove a file.
RM = /opt/cmake-4.0.1-linux-x86_64/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/yunxiao/Desktop/SensorHub_UART

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/yunxiao/Desktop/SensorHub_UART

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/cmake-4.0.1-linux-x86_64/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/cmake-4.0.1-linux-x86_64/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yunxiao/Desktop/SensorHub_UART/CMakeFiles /home/yunxiao/Desktop/SensorHub_UART//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yunxiao/Desktop/SensorHub_UART/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SensorHub_UART

# Build rule for target.
SensorHub_UART: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SensorHub_UART
.PHONY : SensorHub_UART

# fast build rule for target.
SensorHub_UART/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SensorHub_UART.dir/build.make CMakeFiles/SensorHub_UART.dir/build
.PHONY : SensorHub_UART/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SensorHub_UART.dir/build.make CMakeFiles/SensorHub_UART.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SensorHub_UART.dir/build.make CMakeFiles/SensorHub_UART.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SensorHub_UART.dir/build.make CMakeFiles/SensorHub_UART.dir/main.cpp.s
.PHONY : main.cpp.s

src/OTA.o: src/OTA.cpp.o
.PHONY : src/OTA.o

# target to build an object file
src/OTA.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SensorHub_UART.dir/build.make CMakeFiles/SensorHub_UART.dir/src/OTA.cpp.o
.PHONY : src/OTA.cpp.o

src/OTA.i: src/OTA.cpp.i
.PHONY : src/OTA.i

# target to preprocess a source file
src/OTA.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SensorHub_UART.dir/build.make CMakeFiles/SensorHub_UART.dir/src/OTA.cpp.i
.PHONY : src/OTA.cpp.i

src/OTA.s: src/OTA.cpp.s
.PHONY : src/OTA.s

# target to generate assembly for a file
src/OTA.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SensorHub_UART.dir/build.make CMakeFiles/SensorHub_UART.dir/src/OTA.cpp.s
.PHONY : src/OTA.cpp.s

src/frame.o: src/frame.cpp.o
.PHONY : src/frame.o

# target to build an object file
src/frame.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SensorHub_UART.dir/build.make CMakeFiles/SensorHub_UART.dir/src/frame.cpp.o
.PHONY : src/frame.cpp.o

src/frame.i: src/frame.cpp.i
.PHONY : src/frame.i

# target to preprocess a source file
src/frame.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SensorHub_UART.dir/build.make CMakeFiles/SensorHub_UART.dir/src/frame.cpp.i
.PHONY : src/frame.cpp.i

src/frame.s: src/frame.cpp.s
.PHONY : src/frame.s

# target to generate assembly for a file
src/frame.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SensorHub_UART.dir/build.make CMakeFiles/SensorHub_UART.dir/src/frame.cpp.s
.PHONY : src/frame.cpp.s

src/msg_manager.o: src/msg_manager.cpp.o
.PHONY : src/msg_manager.o

# target to build an object file
src/msg_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SensorHub_UART.dir/build.make CMakeFiles/SensorHub_UART.dir/src/msg_manager.cpp.o
.PHONY : src/msg_manager.cpp.o

src/msg_manager.i: src/msg_manager.cpp.i
.PHONY : src/msg_manager.i

# target to preprocess a source file
src/msg_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SensorHub_UART.dir/build.make CMakeFiles/SensorHub_UART.dir/src/msg_manager.cpp.i
.PHONY : src/msg_manager.cpp.i

src/msg_manager.s: src/msg_manager.cpp.s
.PHONY : src/msg_manager.s

# target to generate assembly for a file
src/msg_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SensorHub_UART.dir/build.make CMakeFiles/SensorHub_UART.dir/src/msg_manager.cpp.s
.PHONY : src/msg_manager.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... SensorHub_UART"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/OTA.o"
	@echo "... src/OTA.i"
	@echo "... src/OTA.s"
	@echo "... src/frame.o"
	@echo "... src/frame.i"
	@echo "... src/frame.s"
	@echo "... src/msg_manager.o"
	@echo "... src/msg_manager.i"
	@echo "... src/msg_manager.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

